/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FarmsRouteImport } from './routes/farms'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiScanRouteImport } from './routes/api/ai/scan'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsRoute = FarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiScanRoute = ApiAiScanRouteImport.update({
  id: '/api/ai/scan',
  path: '/api/ai/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/farms': typeof FarmsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/weather': typeof WeatherRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/scan': typeof ApiAiScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/farms': typeof FarmsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/weather': typeof WeatherRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/scan': typeof ApiAiScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/farms': typeof FarmsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/weather': typeof WeatherRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/scan': typeof ApiAiScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/crops'
    | '/dashboard'
    | '/farms'
    | '/login'
    | '/market'
    | '/scanner'
    | '/signup'
    | '/weather'
    | '/api/ai/chat'
    | '/api/ai/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/crops'
    | '/dashboard'
    | '/farms'
    | '/login'
    | '/market'
    | '/scanner'
    | '/signup'
    | '/weather'
    | '/api/ai/chat'
    | '/api/ai/scan'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/crops'
    | '/dashboard'
    | '/farms'
    | '/login'
    | '/market'
    | '/scanner'
    | '/signup'
    | '/weather'
    | '/api/ai/chat'
    | '/api/ai/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CropsRoute: typeof CropsRoute
  DashboardRoute: typeof DashboardRoute
  FarmsRoute: typeof FarmsRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  ScannerRoute: typeof ScannerRoute
  SignupRoute: typeof SignupRoute
  WeatherRoute: typeof WeatherRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiScanRoute: typeof ApiAiScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/scan': {
      id: '/api/ai/scan'
      path: '/api/ai/scan'
      fullPath: '/api/ai/scan'
      preLoaderRoute: typeof ApiAiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CropsRoute: CropsRoute,
  DashboardRoute: DashboardRoute,
  FarmsRoute: FarmsRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  ScannerRoute: ScannerRoute,
  SignupRoute: SignupRoute,
  WeatherRoute: WeatherRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiScanRoute: ApiAiScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
